name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker container
      run: |
        docker pull dshay22/my-cpp-ci:latest
        docker run --name cpp-ci-container -v $(pwd):/workspace -w /workspace dshay22/my-cpp-ci:latest bash -c "
          set -e
          
          g++ --version

          cppcheck --enable=all --inconclusive --error-exitcode=1 --suppress=missingIncludeSystem .

          clang-format --version
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror
          
          cd processor
          cmake .
          cmake --build .
          ctest
        "
    - name: Clean up
      run: docker rm cpp-ci-container