name: C/C++ CI

on:
  push:
    branches: [ "*" ]

jobs:
  build-format:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t cpp-ci-container .

    # Setup 
    - name: Run Docker, Check formatting, and CppCheck
      run: |
        docker run --rm cpp-ci-container bash -c "
          set -e
          
          g++ --version

          clang-format --version
          cd processor
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror
          
          mkdir -p build &&
          cd build &&
          cmake .. &&
          cmake --build .. &&
          ctest
        "
    - name: Clean up
      run: docker rm cpp-ci-container

  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t cpp-ci-container .

    # Run the container and execute tests
    - name: Run tests in Docker container
      run: |
        docker run --rm cpp-ci-container bash -c "
        mkdir -p processor/build &&
        cd processor/build &&
        cmake .. &&
        cmake --build . &&
        ./test_math_functions
        "